# Base working stage
FROM node:18-slim AS base
RUN apt-get update && \
    npm install -g pnpm
WORKDIR /app

###################
## Data Stage — download ENS Subgraph rainbow table archive & checksum
###################

FROM base AS db-data
ADD "https://bucket.ensrainbow.io/ens_names.sql.gz" ./ens_names.sql.gz
ADD "https://bucket.ensrainbow.io/ens_names.sql.gz.sha256sum" ./ens_names.sql.gz.sha256sum
ADD "https://bucket.ensrainbow.io/THE_GRAPH_LICENSE.txt" ./THE_GRAPH_LICENSE.txt
RUN sha256sum -c ens_names.sql.gz.sha256sum

###################
## Dependencies Stage — standard monorepo pnpm install from base
###################

FROM base AS ingest-deps

COPY pnpm-workspace.yaml ./
COPY package.json pnpm-lock.yaml ./
COPY packages ./packages
COPY apps ./apps

RUN pnpm install --frozen-lockfile

###################
## Runtime Stage — ingest to produce data dir artifact
###################

FROM ingest-deps AS ingest

WORKDIR /app/apps/ensrainbow
# copy ens_names.sql.gz from db-data
COPY --from=db-data /app/ens_names.sql.gz .
COPY --from=db-data /app/THE_GRAPH_LICENSE.txt .

# produce the data dir artifact
RUN pnpm run ingest

# cleanup input file to reduce image size
RUN rm ens_names.sql.gz

###################
## Output Image — just the data dir
###################

FROM base AS ensrainbow-data

COPY --from=ingest /app/apps/ensrainbow/data ./data
